#!/usr/bin/env python

"""
tsleep, aka "TQDM sleep"

Pause execution for a given number of seconds, showing a tqdm progress bar.

You may need to install the "python3-tqdm" package
"""

import time
import argparse
from tqdm import tqdm

def parse_args():
    parser = argparse.ArgumentParser(
        description="Sleep for a specified number of seconds with a progress bar."
    )
    parser.add_argument(
        "seconds",
        type=int,
        help="Total number of seconds to sleep (must be a positive integer)",
    )
    return parser.parse_args()

args = parse_args()
if args.seconds < 1:
    parser.error("seconds must be at least 1")

for _ in tqdm(range(args.seconds), desc="Sleeping", unit="s"):
    time.sleep(1)
